import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { Fragment } from 'react';
import Head from 'next/head';

const MyApp = ({ Component, pageProps }: AppProps) => (
  <Fragment>
    <Head>
      <title>Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Component {...pageProps} />
  </Fragment>
);

export default MyApp;
